import type { SaasContent } from "@/lib/saas/content";
import type { SaasTheme } from "@/lib/saas/theme";
import { pascalCase } from "./schema";

export interface GeneratedFile {
  path: string;
  contents: string;
}

const BANNER = `/** Generated by SCAI Studio — safe to edit after publish. */`;

export function generateSaasSiteFiles(
  slug: string,
  content: SaasContent,
  theme: SaasTheme
): GeneratedFile[] {
  const Pascal = pascalCase(slug);

  return [
    {
      path: `src/lib/sites/${slug}/content.ts`,
      contents: `import type { SaasContent } from "@/lib/saas/content";

${BANNER}
export const ${Pascal}SaasContent: SaasContent = ${JSON.stringify(content, null, 2)};
`,
    },
    {
      path: `src/lib/sites/${slug}/theme.ts`,
      contents: `import type { SaasTheme } from "@/lib/saas/theme";

${BANNER}
export const ${Pascal}SaasTheme: SaasTheme = ${JSON.stringify(theme, null, 2)};
`,
    },
    {
      path: `src/lib/sites/${slug}/content.json`,
      contents: JSON.stringify({ slug, templateId: "saas", content, theme }, null, 2) + "\n",
    },
    {
      path: `src/app/${slug}/page.tsx`,
      contents: `import type { Metadata } from "next";
import SaasHeader from "@/components/saas/Header";
import SaasHero from "@/components/saas/Hero";
import ProductDescription from "@/components/saas/ProductDescription";
import Tools from "@/components/saas/Tools";
import Workflow from "@/components/saas/Workflow";
import Testimonials from "@/components/saas/Testimonials";
import Pricing from "@/components/saas/Pricing";
import Blog from "@/components/saas/Blog";
import FAQ from "@/components/saas/FAQ";
import FinalCTA from "@/components/saas/FinalCTA";
import Footer from "@/components/saas/Footer";
import ElementorAnimations from "@/components/saas/ElementorAnimations";
import { SaasStyles } from "@/components/saas/SaasStyles";
import { SaasContentProvider } from "@/components/saas/SaasPreviewProvider";
import { SaasRoot } from "@/components/saas/SaasRoot";
import { ${Pascal}SaasContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}SaasTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/saas/saas.css";

export const metadata: Metadata = {
  title: content.metadata.title,
  description: content.metadata.description,
  icons: { icon: content.favicon },
};

export default function Page() {
  return (
    <>
      <SaasStyles />
      <SaasRoot theme={theme}>
        <SaasContentProvider content={content}>
          <ElementorAnimations />
          <SaasHeader />
          <main>
            <div
              data-elementor-type="wp-page"
              data-elementor-id="4837"
              className="elementor elementor-4837"
              data-elementor-post-type="page"
            >
              <SaasHero />
              <ProductDescription />
              <Tools />
              <Workflow />
              <Testimonials />
              <Pricing />
              <Blog />
              <FAQ />
              <FinalCTA />
            </div>
          </main>
          <Footer />
        </SaasContentProvider>
      </SaasRoot>
    </>
  );
}
`,
    },
  ];
}
