import type { LocalContent } from "@/lib/local/content";
import type { LocalTheme } from "@/lib/local/theme";
import { pascalCase } from "./schema";

export interface GeneratedFile {
  path: string;
  contents: string;
}

const BANNER = `/** Generated by SCAI Studio — safe to edit after publish. */`;

export function generateLocalSiteFiles(slug: string, content: LocalContent, theme: LocalTheme): GeneratedFile[] {
  const Pascal = pascalCase(slug);

  return [
    {
      path: `src/lib/sites/${slug}/content.ts`,
      contents: `import type { LocalContent } from "@/lib/local/content";

${BANNER}
export const ${Pascal}LocalContent: LocalContent = ${JSON.stringify(content, null, 2)};
`,
    },
    {
      path: `src/lib/sites/${slug}/theme.ts`,
      contents: `import type { LocalTheme } from "@/lib/local/theme";

${BANNER}
export const ${Pascal}LocalTheme: LocalTheme = ${JSON.stringify(theme, null, 2)};
`,
    },
    {
      path: `src/lib/sites/${slug}/content.json`,
      contents: JSON.stringify({ slug, templateId: "local", content, theme }, null, 2) + "\n",
    },
    {
      path: `src/app/${slug}/page.tsx`,
      contents: `import type { Metadata } from "next";
import { LocalHeader } from "@/components/local/Header";
import { LocalHero } from "@/components/local/Hero";
import { ServicesSection } from "@/components/local/ServicesSection";
import { ReviewsSection } from "@/components/local/ReviewsSection";
import { GallerySection } from "@/components/local/GallerySection";
import { BlogSection } from "@/components/local/BlogSection";
import { FAQSection } from "@/components/local/FAQSection";
import { StatsCTASection } from "@/components/local/StatsCTASection";
import { LocalFooter } from "@/components/local/Footer";
import { LocalContentProvider } from "@/components/local/LocalContentProvider";
import { LocalRoot } from "@/components/local/LocalRoot";
import { ${Pascal}LocalContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}LocalTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/local/header-footer.css";
import "@/styles/local/hero.css";
import "@/styles/local/sections.css";

export const metadata: Metadata = {
  title: content.metadata.title,
  description: content.metadata.description,
  icons: { icon: content.favicon },
};

export default function Page() {
  return (
    <LocalRoot theme={theme}>
      <LocalContentProvider content={content}>
        <div className="fb-has-sticky-bar">
          <LocalHeader />
          <main>
            <LocalHero />
            <ServicesSection />
            <ReviewsSection />
            <GallerySection />
            <BlogSection />
            <FAQSection />
            <StatsCTASection />
          </main>
          <LocalFooter />
        </div>
      </LocalContentProvider>
    </LocalRoot>
  );
}
`,
    },
  ];
}
