import type { NicheTemplateContent } from "@/lib/niche-template/content";
import type { NicheTheme } from "@/lib/niche-template/theme";
import { pascalCase } from "./schema";

export interface GeneratedFile {
  path: string;
  contents: string;
}

/**
 * Single source of truth for "what files a niche-template site needs."
 * Used by both scripts/scaffold-niche-site.ts (developer CLI, TODO
 * placeholders) and /api/builder/publish (wizard, real generated content) —
 * whichever caller you are, you get the exact same route files, and
 * content/theme files built from whatever NicheTemplateContent/NicheTheme
 * object you hand in.
 */

const GENERATED_BANNER = `/**
 * Generated by the niche-template builder. Safe to hand-edit afterwards —
 * this file is only written once at scaffold/publish time, never
 * overwritten automatically.
 */`;

export function getThemeFile(slug: string, theme: NicheTheme): GeneratedFile {
  const Pascal = pascalCase(slug);
  return {
    path: `src/lib/sites/${slug}/theme.ts`,
    contents: `import type { NicheTheme } from "@/lib/niche-template/theme";

${GENERATED_BANNER}
export const ${Pascal}Theme: NicheTheme = ${JSON.stringify(theme, null, 2)};
`,
  };
}

export function getContentFile(slug: string, content: NicheTemplateContent): GeneratedFile {
  const Pascal = pascalCase(slug);
  return {
    path: `src/lib/sites/${slug}/content.ts`,
    contents: `import type { NicheTemplateContent } from "@/lib/niche-template/content";

${GENERATED_BANNER}
export const ${Pascal}Content: NicheTemplateContent = ${JSON.stringify(content, null, 2)};
`,
  };
}

/**
 * A JSON sidecar mirroring the same data as content.ts/theme.ts — the
 * builder reads/writes this (safe, structured) when a user re-opens a
 * published site to edit it, instead of parsing TypeScript source.
 */
export function getContentJsonFile(
  slug: string,
  content: NicheTemplateContent,
  theme: NicheTheme
): GeneratedFile {
  return {
    path: `src/lib/sites/${slug}/content.json`,
    contents: JSON.stringify({ slug, content, theme }, null, 2) + "\n",
  };
}

export function getRouteFiles(slug: string): GeneratedFile[] {
  const Pascal = pascalCase(slug);

  return [
    {
      path: `src/app/${slug}/layout.tsx`,
      contents: `import type { Metadata } from "next";
import "@/styles/niche-template/niche-template.css";
import { ${Pascal}Content as content } from "@/lib/sites/${slug}/content";

export const metadata: Metadata = {
  title: content.metadata.title,
  description: content.metadata.description,
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
`,
    },
    {
      path: `src/app/${slug}/page.tsx`,
      contents: `import {
  NicheTemplateRoot,
  NicheTemplateHeader,
  NicheTemplateHero,
  NicheTemplateCategoryTiles,
  NicheTemplateArticleGrid,
  NicheTemplateFooter,
} from "@/components/niche-template";
import { ${Pascal}Theme as theme } from "@/lib/sites/${slug}/theme";
import { ${Pascal}Content as content } from "@/lib/sites/${slug}/content";

export default function ${Pascal}Home() {
  return (
    <NicheTemplateRoot theme={theme}>
      <NicheTemplateHeader content={content} />
      <main>
        <NicheTemplateHero content={content} />
        <NicheTemplateCategoryTiles content={content} />
        <NicheTemplateArticleGrid content={content} basePath="/${slug}/article" />
      </main>
      <NicheTemplateFooter content={content} />
    </NicheTemplateRoot>
  );
}
`,
    },
    {
      path: `src/app/${slug}/category/[slug]/page.tsx`,
      contents: `import { notFound } from "next/navigation";
import {
  NicheTemplateRoot,
  NicheTemplateHeader,
  NicheTemplateCategoryPage,
  NicheTemplateFooter,
} from "@/components/niche-template";
import { getCategoryBySlug } from "@/lib/niche-template/content";
import { ${Pascal}Theme as theme } from "@/lib/sites/${slug}/theme";
import { ${Pascal}Content as content } from "@/lib/sites/${slug}/content";

export function generateStaticParams() {
  return content.categories.map((category) => ({ slug: category.slug }));
}

export default async function ${Pascal}Category({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const category = getCategoryBySlug(content, slug);
  if (!category) notFound();

  return (
    <NicheTemplateRoot theme={theme}>
      <NicheTemplateHeader content={content} />
      <main>
        <NicheTemplateCategoryPage content={content} category={category} basePath="/${slug}/article" />
      </main>
      <NicheTemplateFooter content={content} />
    </NicheTemplateRoot>
  );
}
`,
    },
    {
      path: `src/app/${slug}/article/[slug]/page.tsx`,
      contents: `import { notFound } from "next/navigation";
import {
  NicheTemplateRoot,
  NicheTemplateHeader,
  NicheTemplateSingleArticle,
  NicheTemplateFooter,
} from "@/components/niche-template";
import { ${Pascal}Theme as theme } from "@/lib/sites/${slug}/theme";
import { ${Pascal}Content as content } from "@/lib/sites/${slug}/content";

export function generateStaticParams() {
  return content.articles.map((article) => ({ slug: article.slug }));
}

export default async function ${Pascal}Article({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = content.articles.find((a) => a.slug === slug);
  if (!article) notFound();

  return (
    <NicheTemplateRoot theme={theme}>
      <NicheTemplateHeader content={content} />
      <main>
        <NicheTemplateSingleArticle content={content} article={article} />
      </main>
      <NicheTemplateFooter content={content} />
    </NicheTemplateRoot>
  );
}
`,
    },
    {
      path: `src/app/${slug}/page/[slug]/page.tsx`,
      contents: `import { notFound } from "next/navigation";
import {
  NicheTemplateRoot,
  NicheTemplateHeader,
  NicheTemplateStaticPage,
  NicheTemplateContactPage,
  NicheTemplateFooter,
} from "@/components/niche-template";
import { getPageBySlug } from "@/lib/niche-template/content";
import { ${Pascal}Theme as theme } from "@/lib/sites/${slug}/theme";
import { ${Pascal}Content as content } from "@/lib/sites/${slug}/content";

export function generateStaticParams() {
  return content.pages.map((page) => ({ slug: page.slug }));
}

export default async function ${Pascal}Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const page = getPageBySlug(content, slug);
  if (!page) notFound();

  return (
    <NicheTemplateRoot theme={theme}>
      <NicheTemplateHeader content={content} />
      <main>
        {slug === "contact" ? (
          <NicheTemplateContactPage content={content} page={page} />
        ) : (
          <NicheTemplateStaticPage content={content} page={page} />
        )}
      </main>
      <NicheTemplateFooter content={content} />
    </NicheTemplateRoot>
  );
}
`,
    },
  ];
}

export interface SiteFilesOptions {
  slug: string;
  content: NicheTemplateContent;
  theme: NicheTheme;
  /** Also emit the src/lib/sites/<slug>/content.json sidecar (default true). */
  withJsonSidecar?: boolean;
}

/** All files a complete, working site needs — the one function both the CLI script and the publish API call. */
export function generateAllSiteFiles({
  slug,
  content,
  theme,
  withJsonSidecar = true,
}: SiteFilesOptions): GeneratedFile[] {
  const files = [getThemeFile(slug, theme), getContentFile(slug, content), ...getRouteFiles(slug)];
  if (withJsonSidecar) files.push(getContentJsonFile(slug, content, theme));
  return files;
}
