import type { SaasDraftContent } from "./deriveSaas";
import { pascalCase } from "./schema";

export interface GeneratedFile {
  path: string;
  contents: string;
}

const BANNER = `/** Generated by SCAI Studio */`;

export function generateSaasSiteFiles(slug: string, content: SaasDraftContent): GeneratedFile[] {
  const Pascal = pascalCase(slug);

  return [
    {
      path: `src/lib/sites/${slug}/content.ts`,
      contents: `import type { SaasDraftContent } from "@/lib/builder/deriveSaas";

${BANNER}
export const ${Pascal}SaasContent = ${JSON.stringify(content, null, 2)} as const satisfies SaasDraftContent;
`,
    },
    {
      path: `src/lib/sites/${slug}/content.json`,
      contents: JSON.stringify({ slug, templateId: "saas", content }, null, 2) + "\n",
    },
    {
      path: `src/app/${slug}/page.tsx`,
      contents: `import SaasHeader from "@/components/saas/Header";
import SaasHero from "@/components/saas/Hero";
import ProductDescription from "@/components/saas/ProductDescription";
import Tools from "@/components/saas/Tools";
import Workflow from "@/components/saas/Workflow";
import Features from "@/components/saas/Features";
import Testimonials from "@/components/saas/Testimonials";
import Pricing from "@/components/saas/Pricing";
import Blog from "@/components/saas/Blog";
import FAQ from "@/components/saas/FAQ";
import FinalCTA from "@/components/saas/FinalCTA";
import Footer from "@/components/saas/Footer";
import { SaasPreviewProvider } from "@/components/saas/SaasPreviewProvider";
import { ${Pascal}SaasContent as content } from "@/lib/sites/${slug}/content";
import "@/styles/saas/saas.css";

export default function Page() {
  return (
    <SaasPreviewProvider content={content}>
      <SaasHeader />
      <main>
        <SaasHero />
        <ProductDescription />
        <Tools />
        <Workflow />
        <Features />
        <Testimonials />
        <Pricing />
        <Blog />
        <FAQ />
        <FinalCTA />
      </main>
      <Footer />
    </SaasPreviewProvider>
  );
}
`,
    },
    {
      path: `src/app/${slug}/layout.tsx`,
      contents: `import type { Metadata } from "next";
import { ${Pascal}SaasContent as content } from "@/lib/sites/${slug}/content";

export const metadata: Metadata = {
  title: content.metadata.title,
  description: content.metadata.description,
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
`,
    },
  ];
}
