import type { EcommerceContent } from "@/lib/ecommerce/content";
import type { EcommerceTheme } from "@/lib/ecommerce/theme";
import { pascalCase } from "./schema";

export interface GeneratedFile {
  path: string;
  contents: string;
}

const BANNER = `/** Generated by SCAI Studio — safe to edit after publish. */`;

export function generateEcommerceSiteFiles(
  slug: string,
  content: EcommerceContent,
  theme: EcommerceTheme
): GeneratedFile[] {
  const Pascal = pascalCase(slug);

  return [
    {
      path: `src/lib/sites/${slug}/content.ts`,
      contents: `import type { EcommerceContent } from "@/lib/ecommerce/content";

${BANNER}
export const ${Pascal}EcommerceContent: EcommerceContent = ${JSON.stringify(content, null, 2)};
`,
    },
    {
      path: `src/lib/sites/${slug}/theme.ts`,
      contents: `import type { EcommerceTheme } from "@/lib/ecommerce/theme";

${BANNER}
export const ${Pascal}EcommerceTheme: EcommerceTheme = ${JSON.stringify(theme, null, 2)};
`,
    },
    {
      path: `src/lib/sites/${slug}/content.json`,
      contents: JSON.stringify({ slug, templateId: "ecommerce", content, theme }, null, 2) + "\n",
    },
    {
      path: `src/app/${slug}/page.tsx`,
      contents: `import type { Metadata } from "next";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { Hero } from "@/components/ecommerce/home/Hero";
import { TopProducts } from "@/components/ecommerce/home/TopProducts";
import { FeaturePrimary, FeatureSecondary } from "@/components/ecommerce/home/FeaturePrimary";
import { OurProducts } from "@/components/ecommerce/home/OurProducts";
import { Categories } from "@/components/ecommerce/home/Categories";
import { Blog } from "@/components/ecommerce/home/Blog";
import { FAQ } from "@/components/ecommerce/home/FAQ";
import { CTABanner } from "@/components/ecommerce/home/CTABanner";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

export const metadata: Metadata = {
  title: content.metadata.title,
  description: content.metadata.description,
  icons: { icon: content.favicon },
};

export default function Page() {
  return (
    <EcommerceShell content={content} theme={theme}>
      <main>
        <Hero />
        <TopProducts />
        <FeaturePrimary />
        <OurProducts />
        <Categories />
        <FeatureSecondary />
        <Blog />
        <FAQ />
        <CTABanner />
      </main>
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/shop/page.tsx`,
      contents: `import type { Metadata } from "next";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { ShopView } from "@/components/ecommerce/shop/ShopView";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

export const metadata: Metadata = {
  title: content.shop.metadata.title,
  description: content.shop.metadata.description,
  icons: { icon: content.favicon },
};

export default function ShopPage() {
  return (
    <EcommerceShell content={content} theme={theme}>
      <ShopView />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/product/[slug]/page.tsx`,
      contents: `import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { ProductDetailView } from "@/components/ecommerce/product/ProductDetailView";
import { getProductBySlug } from "@/lib/ecommerce/product";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return content.shop.products.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const product = getProductBySlug(content, slug);
  if (!product) return { title: "Product not found" };
  return {
    title: \`\${product.title} — \${content.siteName}\`,
    description: product.shortDescription || content.metadata.description,
    icons: { icon: content.favicon },
  };
}

export default async function ProductPage({ params }: Props) {
  const { slug } = await params;
  if (!getProductBySlug(content, slug)) notFound();

  return (
    <EcommerceShell content={content} theme={theme}>
      <ProductDetailView slug={slug} />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/cart/page.tsx`,
      contents: `import type { Metadata } from "next";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { CartPageView } from "@/components/ecommerce/cart/CartPageView";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

export const metadata: Metadata = {
  title: \`Cart — \${content.siteName}\`,
  description: "Review items in your shopping cart.",
  icons: { icon: content.favicon },
};

export default function CartPage() {
  return (
    <EcommerceShell content={content} theme={theme} cartInitiallyOpen>
      <CartPageView />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/checkout/page.tsx`,
      contents: `import type { Metadata } from "next";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { CheckoutView } from "@/components/ecommerce/checkout/CheckoutView";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

export const metadata: Metadata = {
  title: \`Checkout — \${content.siteName}\`,
  description: "Complete your order — shipping, payment, and review.",
  icons: { icon: content.favicon },
};

export default function CheckoutPage() {
  return (
    <EcommerceShell content={content} theme={theme}>
      <CheckoutView />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/track/page.tsx`,
      contents: `import type { Metadata } from "next";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { TrackView } from "@/components/ecommerce/track/TrackView";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

export const metadata: Metadata = {
  title: content.track.metadata.title,
  description: content.track.metadata.description,
  icons: { icon: content.favicon },
};

export default function TrackPage() {
  return (
    <EcommerceShell content={content} theme={theme}>
      <TrackView />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/legal/[slug]/page.tsx`,
      contents: `import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { LegalPolicyView } from "@/components/ecommerce/legal/LegalPolicyView";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import { findLegalPage } from "@/lib/ecommerce/legal-sample";
import "@/styles/ecommerce/ecommerce.css";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return content.legal.pages.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const page = findLegalPage(content.legal, slug);
  if (!page) return { title: "Not found" };
  return {
    title: page.metadata.title,
    description: page.metadata.description,
    icons: { icon: content.favicon },
  };
}

export default async function LegalPage({ params }: Props) {
  const { slug } = await params;
  if (!findLegalPage(content.legal, slug)) notFound();
  return (
    <EcommerceShell content={content} theme={theme}>
      <LegalPolicyView slug={slug} />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/about/page.tsx`,
      contents: `import type { Metadata } from "next";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { AboutView } from "@/components/ecommerce/about/AboutView";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

export const metadata: Metadata = {
  title: content.about.metadata.title,
  description: content.about.metadata.description,
  icons: { icon: content.favicon },
};

export default function AboutPage() {
  return (
    <EcommerceShell content={content} theme={theme}>
      <AboutView />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/blog/page.tsx`,
      contents: `import type { Metadata } from "next";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { BlogIndexView } from "@/components/ecommerce/blog/BlogIndexView";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

export const metadata: Metadata = {
  title: content.blog.metadata.title,
  description: content.blog.metadata.description,
  icons: { icon: content.favicon },
};

export default function BlogPage() {
  return (
    <EcommerceShell content={content} theme={theme}>
      <BlogIndexView />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/blog/[slug]/page.tsx`,
      contents: `import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { BlogPostView } from "@/components/ecommerce/blog/BlogPostView";
import { findBlogArticle } from "@/lib/ecommerce/pages-sample";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return content.blog.posts.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = findBlogArticle(content.blog.posts, slug);
  if (!post) return { title: "Not found" };
  return {
    title: \`\${post.title} — \${content.siteName}\`,
    description: post.excerpt,
    icons: { icon: content.favicon },
  };
}

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params;
  if (!findBlogArticle(content.blog.posts, slug)) notFound();
  return (
    <EcommerceShell content={content} theme={theme}>
      <BlogPostView slug={slug} />
    </EcommerceShell>
  );
}
`,
    },
    {
      path: `src/app/${slug}/contact/page.tsx`,
      contents: `import type { Metadata } from "next";
import { EcommerceShell } from "@/components/ecommerce/EcommerceShell";
import { ContactView } from "@/components/ecommerce/contact/ContactView";
import { ${Pascal}EcommerceContent as content } from "@/lib/sites/${slug}/content";
import { ${Pascal}EcommerceTheme as theme } from "@/lib/sites/${slug}/theme";
import "@/styles/ecommerce/ecommerce.css";

export const metadata: Metadata = {
  title: content.contact.metadata.title,
  description: content.contact.metadata.description,
  icons: { icon: content.favicon },
};

export default function ContactPage() {
  return (
    <EcommerceShell content={content} theme={theme}>
      <ContactView />
    </EcommerceShell>
  );
}
`,
    },
  ];
}
