import { NextRequest, NextResponse } from "next/server";
import { existsSync } from "fs";
import path from "path";
import { BuilderDraftSchema } from "@/lib/builder/schema";
import { deriveContent, deriveTheme } from "@/lib/builder/derive";
import { generateAllSiteFiles } from "@/lib/builder/generateSiteFiles";
import { extractDraftImages } from "@/lib/builder/extractImages";
import { isSlugTaken, upsertEntry, type SiteRegistryEntry } from "@/lib/sites/registry";
import { isGithubConfigured, commitFilesAndOpenPr, type CommitFile } from "@/lib/builder/github";

/**
 * Validates the full draft, derives the real NicheTemplateContent/Theme,
 * generates every file the site needs (via the same generator the CLI
 * scaffold script uses), and either:
 *  - commits them to a new branch + opens a PR (GITHUB_TOKEN configured), or
 *  - returns a "dry run" describing exactly what would have been written
 *    (no credentials configured — keeps the feature testable/demoable).
 */
export async function POST(req: NextRequest) {
  let body: { draft?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const parsed = BuilderDraftSchema.safeParse(body.draft);
  if (!parsed.success) {
    return NextResponse.json(
      {
        error: "Draft is incomplete or invalid.",
        issues: parsed.error.issues.map((i) => ({ path: i.path.join("."), message: i.message })),
      },
      { status: 400 }
    );
  }
  const draft = parsed.data;

  if (isSlugTaken(draft.slug)) {
    return NextResponse.json(
      { error: `Slug "${draft.slug}" is already used by a published site. Choose a different URL slug.` },
      { status: 409 }
    );
  }
  try {
    if (existsSync(path.join(process.cwd(), "src", "app", draft.slug))) {
      return NextResponse.json(
        { error: `A route already exists at /${draft.slug} in this repo. Choose a different URL slug.` },
        { status: 409 }
      );
    }
  } catch {
    // fs unavailable in this runtime — the registry check above is the source of truth there.
  }

  const rawContent = deriveContent(draft);
  const theme = deriveTheme(draft);
  const { content, imageFiles } = await extractDraftImages(draft.slug, rawContent);

  const siteFiles = generateAllSiteFiles({ slug: draft.slug, content, theme });
  const textFiles: CommitFile[] = siteFiles.map((f) => ({ path: f.path, content: f.contents, encoding: "utf-8" }));
  const allFiles = [...textFiles, ...imageFiles];

  const now = new Date().toISOString();
  const entry: SiteRegistryEntry = {
    slug: draft.slug,
    siteName: draft.siteName,
    createdAt: now,
    updatedAt: now,
    status: "draft-pr",
  };

  if (!isGithubConfigured()) {
    return NextResponse.json({
      dryRun: true,
      note: "GITHUB_TOKEN/GITHUB_REPO are not configured — files were generated and validated but nothing was committed. Set both env vars to enable real publishing.",
      files: allFiles.map((f) => ({ path: f.path, bytes: f.content.length, encoding: f.encoding })),
    });
  }

  try {
    const branchName = `builder/${draft.slug}-${Date.now()}`;
    const registryFile: CommitFile = {
      path: "src/lib/sites/registry.json",
      content: JSON.stringify(upsertEntry(entry), null, 2) + "\n",
      encoding: "utf-8",
    };

    const { prUrl } = await commitFilesAndOpenPr({
      branchName,
      commitMessage: `feat: scaffold ${draft.siteName} (/${draft.slug}) via site builder`,
      prTitle: `Add new site: ${draft.siteName} (/${draft.slug})`,
      prBody: [
        "Generated by the /studio site builder.",
        "",
        `- Site: ${draft.siteName}`,
        `- Slug: /${draft.slug}`,
        `- Categories: ${content.categories.map((c) => c.label).join(", ")}`,
        `- Articles: ${content.articles.length}`,
        `- Generated images: ${imageFiles.length}`,
        "",
        "Review the diff, then merge to deploy.",
      ].join("\n"),
      files: [...allFiles, registryFile],
    });

    return NextResponse.json({ prUrl, branch: branchName });
  } catch (err) {
    console.error("[api/builder/publish]", err);
    return NextResponse.json({ error: err instanceof Error ? err.message : "Publish failed." }, { status: 502 });
  }
}
